package com.proyectoplanu.proyectoplanu.gui;

import com.proyectoplanu.proyectoplanu.Activity;
import com.proyectoplanu.proyectoplanu.Calendary;
import java.awt.CardLayout;
import java.util.ArrayList;

public class GuiActivity extends javax.swing.JFrame 
{
    private CardLayout cardLayout;
    private GuiCurrentDay guiCurrentDay;
    private GuiAddActivity guiAddActivity;
    
    private int day;
    private int month;
    private int year;
    
    private GuiMenu guiMenu;
    
    public GuiActivity(Calendary calendary, GuiMenu guiMenu)
    {
        this.guiMenu = guiMenu;
        initComponents();
        
        cardLayout = new CardLayout();
        guiCurrentDay = new GuiCurrentDay();
        guiAddActivity = new GuiAddActivity(calendary, this);
        
        mainPanel.add(guiCurrentDay, "GuiCurrentDay");
        mainPanel.add(guiAddActivity, "GuiAddActivity");
        
        mainPanel.setLayout(cardLayout);
    }
    
    public void openCurrentDay(ArrayList<Activity> currentActivities)
    {
        if (currentActivities.isEmpty())
        {
            menuBar.setVisible(false);
            guiCurrentDay.setVisible(false);
            guiAddActivity.showReturnButton(false);
            guiAddActivity.updateManagers();
            guiAddActivity.setDate(day, month, year);
            guiAddActivity.setVisible(true);
            cardLayout.show(mainPanel, "GuiAddActivity");
            return;
        }
        
        menuBar.setVisible(true);
        guiCurrentDay.setVisible(true);
        guiAddActivity.showReturnButton(true);
        guiAddActivity.setVisible(false);
        guiCurrentDay.setCurrentActivities(currentActivities);
        cardLayout.show(mainPanel, "GuiCurrentDay");
    }
    
    public void setDate(int day, int month, int year)
    {
        this.day = day;
        this.month = month;
        this.year = year;
    }
    
    public void returnToCurrentDay(boolean value)
    {
        if (value)
        {
            menuBar.setVisible(true);
            guiCurrentDay.setVisible(true);
            guiAddActivity.showReturnButton(true);
            guiAddActivity.setVisible(false);
            cardLayout.show(mainPanel, "GuiCurrentDay");
        }
        else
        {
            menuBar.setVisible(false);
            guiCurrentDay.setVisible(false);
            guiAddActivity.updateManagers();
            guiAddActivity.setDate(day, month, year);
            guiAddActivity.setVisible(true);
            cardLayout.show(mainPanel, "GuiAddActivity");
        }
    }
    
    public void updateCurrentDayActivities(ArrayList<Activity> activities)
    {
        guiCurrentDay.setCurrentActivities(activities);
        guiMenu.updateCalendary();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        addActivityButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        addActivityButton.setText("Agregar Actividad");
        addActivityButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addActivityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addActivityButtonMouseClicked(evt);
            }
        });
        menuBar.add(addActivityButton);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActivityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addActivityButtonMouseClicked
        returnToCurrentDay(false);
    }//GEN-LAST:event_addActivityButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu addActivityButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
