package com.proyectoplanu.proyectoplanu.gui;

import com.proyectoplanu.proyectoplanu.Activity;
import com.proyectoplanu.proyectoplanu.Manager;
import com.proyectoplanu.proyectoplanu.Student;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

public class GuiCurrentDay extends javax.swing.JPanel 
{
    private ArrayList<Activity> currentActivities;
    
    public GuiCurrentDay()
    {
        initComponents();
    }

    public void setCurrentActivities(ArrayList<Activity> currentActivities)
    {
        this.currentActivities = currentActivities;
        activityList.removeAll();
        DefaultListModel<String> model = new DefaultListModel();
        for (Activity activity : currentActivities)
        {
            model.addElement(activity.getName());
        }
        activityList.setModel(model);
        setSelectedActivity(0);
    }
    
    public ArrayList<Activity> getCurrentActivities()
    {
        return currentActivities;
    }
    
    private void setSelectedActivity(int index)
    {
        Activity activity = currentActivities.get(index);
        
        nameLabel.setText(activity.getName());
        dateLabel.setText(activity.getDate());
        
        String[] hourData = Float.toString(activity.getHour()).split("\\.");
        String hour = Float.parseFloat(hourData[0]) <= 9 ? "0" + hourData[0] : hourData[0];
        hour += ":";
        hour +=  Float.parseFloat(hourData[1]) <= 9 ? hourData[1] + "0" : hourData[1];
        hourLabel.setText(hour);
        
        Manager manager = activity.getManager();
        managerNameLabel.setText(manager.getName());
        managerAgeLabel.setText(manager.getAge() + " años");
        managerRutLabel.setText(manager.getRut());
        
        String text = "<html>";
        for (Student student : activity.getStudents())
        {
            text += student.getName() + "<BR>";
        }
        text += "</html>";
        asistentes.setText(text);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        activityList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        hourLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        asistentesLabel = new javax.swing.JLabel();
        managerNameLabel = new javax.swing.JLabel();
        managerAgeLabel = new javax.swing.JLabel();
        managerRutLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        managerLabel = new javax.swing.JLabel();
        asistentes = new javax.swing.JLabel();

        activityList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        activityList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        activityList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                activityListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(activityList);

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Actividad");

        dateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("14/07/2022");

        hourLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hourLabel.setText("19:30");

        asistentesLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        asistentesLabel.setText("Asistentes:");

        managerNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        managerNameLabel.setText("Kevin Rojas");

        managerAgeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        managerAgeLabel.setText("21 años");

        managerRutLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        managerRutLabel.setText("20410798-k");

        managerLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        managerLabel.setText("Manager:");

        asistentes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        asistentes.setText("Kevin Rojas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(asistentesLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(managerRutLabel)
                                    .addComponent(managerNameLabel)
                                    .addComponent(managerAgeLabel))))
                        .addGap(0, 229, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(asistentes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(hourLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(managerLabel)
                    .addContainerGap(271, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(dateLabel)
                .addGap(18, 18, 18)
                .addComponent(hourLabel)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(managerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managerAgeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managerRutLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asistentesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(asistentes)
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(managerLabel)
                    .addContainerGap(272, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void activityListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_activityListValueChanged
        int index = activityList.getSelectedIndex();
        setSelectedActivity(index);
    }//GEN-LAST:event_activityListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> activityList;
    private javax.swing.JLabel asistentes;
    private javax.swing.JLabel asistentesLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel managerAgeLabel;
    private javax.swing.JLabel managerLabel;
    private javax.swing.JLabel managerNameLabel;
    private javax.swing.JLabel managerRutLabel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
