package com.proyectoplanu.proyectoplanu.gui;

import com.proyectoplanu.proyectoplanu.*;
import com.proyectoplanu.proyectoplanu.strategy.*;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;

public class GuiMenu extends javax.swing.JFrame 
{
    private static GuiMenu Instance = null;
    
    private Calendary calendary;
    
    private int year = 2022;
    private int month = 6;
   
    private GuiActivity guiActivity;
    
    private MonthContext monthContext;
    
    public GuiMenu(Calendary calendary) 
    {
        initComponents();
        this.calendary = calendary;
        
        monthContext = new MonthContext(new ThertyDayMonth());
        
        yearSpinner.setValue(year);
        updateCalendary();
        
        guiActivity = new GuiActivity(calendary, this);
    }

    public void updateCalendary()
    {
        Enumeration<AbstractButton> buttons = monthButtons.getElements();
        while (buttons.hasMoreElements())
        {
            AbstractButton button = buttons.nextElement();
            
            String buttonText = button.getText();
            String dayString = buttonText.length() < 2 ? buttonText : buttonText.substring(0, 2);
            int day = Integer.parseInt(dayString);
            String date = Activity.parseDate(day, month, year);
            
            int count = calendary.getActivityCollection().getActivitiesInDate(date).size();
            if (count > 0)
            {
                String text = dayString + " (" + count + ")";
                button.setText(text);
            }
            else
            {
                String text = day <= 9 ? "0" + Integer.toString(day) : Integer.toString(day);
                button.setText(text);
            }
        }
        
        monthContext.setVisibleButtons(day29, day30, day31);
    }
    
    private void dayActionPerformed(int day, javax.swing.JButton button)
    {
        guiActivity.setVisible(true);
        
        ArrayList<Activity> activities = calendary
                .getActivityCollection()
                .getActivitiesInDate(day, month, year);
        guiActivity.setDate(day, month, year);
        guiActivity.openCurrentDay(activities);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monthButtons = new javax.swing.ButtonGroup();
        separatorCalendaryDate = new javax.swing.JSeparator();
        monthLabel = new javax.swing.JLabel();
        yearSpinner = new javax.swing.JSpinner();
        day1 = new javax.swing.JButton();
        day2 = new javax.swing.JButton();
        day3 = new javax.swing.JButton();
        day4 = new javax.swing.JButton();
        day5 = new javax.swing.JButton();
        day6 = new javax.swing.JButton();
        day7 = new javax.swing.JButton();
        day8 = new javax.swing.JButton();
        day9 = new javax.swing.JButton();
        day10 = new javax.swing.JButton();
        day11 = new javax.swing.JButton();
        day12 = new javax.swing.JButton();
        day13 = new javax.swing.JButton();
        day14 = new javax.swing.JButton();
        day15 = new javax.swing.JButton();
        day16 = new javax.swing.JButton();
        day17 = new javax.swing.JButton();
        day18 = new javax.swing.JButton();
        day19 = new javax.swing.JButton();
        day20 = new javax.swing.JButton();
        day21 = new javax.swing.JButton();
        day22 = new javax.swing.JButton();
        day23 = new javax.swing.JButton();
        day24 = new javax.swing.JButton();
        day25 = new javax.swing.JButton();
        day26 = new javax.swing.JButton();
        day27 = new javax.swing.JButton();
        day28 = new javax.swing.JButton();
        day29 = new javax.swing.JButton();
        day30 = new javax.swing.JButton();
        day31 = new javax.swing.JButton();
        lunes = new javax.swing.JLabel();
        martes = new javax.swing.JLabel();
        miercoles = new javax.swing.JLabel();
        jueves = new javax.swing.JLabel();
        viernes = new javax.swing.JLabel();
        sabado = new javax.swing.JLabel();
        domingo = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        previousMonth = new javax.swing.JButton();
        nextMonth = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        monthLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        monthLabel.setText("Junio de");

        yearSpinner.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        yearSpinner.setRequestFocusEnabled(false);
        yearSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yearSpinnerStateChanged(evt);
            }
        });

        day1.setText("01");
        monthButtons.add(day1);
        day1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day1ActionPerformed(evt);
            }
        });

        day2.setText("02");
        monthButtons.add(day2);
        day2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day2ActionPerformed(evt);
            }
        });

        day3.setText("03");
        monthButtons.add(day3);
        day3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day3ActionPerformed(evt);
            }
        });

        day4.setText("04");
        monthButtons.add(day4);
        day4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day4ActionPerformed(evt);
            }
        });

        day5.setText("05");
        monthButtons.add(day5);
        day5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day5ActionPerformed(evt);
            }
        });

        day6.setText("06");
        monthButtons.add(day6);
        day6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day6ActionPerformed(evt);
            }
        });

        day7.setText("07");
        monthButtons.add(day7);
        day7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day7ActionPerformed(evt);
            }
        });

        day8.setText("08");
        monthButtons.add(day8);
        day8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day8ActionPerformed(evt);
            }
        });

        day9.setText("09");
        monthButtons.add(day9);
        day9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day9ActionPerformed(evt);
            }
        });

        day10.setText("10");
        monthButtons.add(day10);
        day10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day10ActionPerformed(evt);
            }
        });

        day11.setText("11");
        monthButtons.add(day11);
        day11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day11ActionPerformed(evt);
            }
        });

        day12.setText("12");
        monthButtons.add(day12);
        day12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day12ActionPerformed(evt);
            }
        });

        day13.setText("13");
        monthButtons.add(day13);
        day13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day13ActionPerformed(evt);
            }
        });

        day14.setText("14");
        monthButtons.add(day14);
        day14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day14ActionPerformed(evt);
            }
        });

        day15.setText("15");
        monthButtons.add(day15);
        day15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day15ActionPerformed(evt);
            }
        });

        day16.setText("16");
        monthButtons.add(day16);
        day16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day16ActionPerformed(evt);
            }
        });

        day17.setText("17");
        monthButtons.add(day17);
        day17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day17ActionPerformed(evt);
            }
        });

        day18.setText("18");
        monthButtons.add(day18);
        day18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day18ActionPerformed(evt);
            }
        });

        day19.setText("19");
        monthButtons.add(day19);
        day19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day19ActionPerformed(evt);
            }
        });

        day20.setText("20");
        monthButtons.add(day20);
        day20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day20.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day20ActionPerformed(evt);
            }
        });

        day21.setText("21");
        monthButtons.add(day21);
        day21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day21ActionPerformed(evt);
            }
        });

        day22.setText("22");
        monthButtons.add(day22);
        day22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day22ActionPerformed(evt);
            }
        });

        day23.setText("23");
        monthButtons.add(day23);
        day23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day23.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day23ActionPerformed(evt);
            }
        });

        day24.setText("24");
        monthButtons.add(day24);
        day24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day24.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day24ActionPerformed(evt);
            }
        });

        day25.setText("25");
        monthButtons.add(day25);
        day25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day25.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day25.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day25.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day25ActionPerformed(evt);
            }
        });

        day26.setText("26");
        monthButtons.add(day26);
        day26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day26.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day26ActionPerformed(evt);
            }
        });

        day27.setText("27");
        monthButtons.add(day27);
        day27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day27.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day27.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day27.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day27ActionPerformed(evt);
            }
        });

        day28.setText("28");
        monthButtons.add(day28);
        day28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day28.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day28.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day28ActionPerformed(evt);
            }
        });

        day29.setText("29");
        monthButtons.add(day29);
        day29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day29.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day29.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day29ActionPerformed(evt);
            }
        });

        day30.setText("30");
        monthButtons.add(day30);
        day30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day30.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day30.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day30ActionPerformed(evt);
            }
        });

        day31.setText("31");
        monthButtons.add(day31);
        day31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        day31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        day31.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        day31.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        day31.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        day31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day31ActionPerformed(evt);
            }
        });

        lunes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lunes.setText("Lunes");

        martes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        martes.setText("Martes");

        miercoles.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        miercoles.setText("Miercoles");

        jueves.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jueves.setText("Jueves");

        viernes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viernes.setText("Viernes");

        sabado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sabado.setText("Sabado");

        domingo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        domingo.setText("Domingo");

        menuLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        menuLabel.setText("Menu");

        previousMonth.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        previousMonth.setText("<");
        previousMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousMonthActionPerformed(evt);
            }
        });

        nextMonth.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nextMonth.setText(">");
        nextMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMonthActionPerformed(evt);
            }
        });

        menuBar.setBackground(new java.awt.Color(51, 51, 51));
        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        fileMenu.setBackground(new java.awt.Color(51, 51, 51));
        fileMenu.setForeground(new java.awt.Color(204, 204, 204));
        fileMenu.setText("Archivo");
        fileMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(separatorCalendaryDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(day8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(day9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(day16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(day23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(day30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(day31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lunes)
                .addGap(65, 65, 65)
                .addComponent(martes)
                .addGap(57, 57, 57)
                .addComponent(miercoles)
                .addGap(55, 55, 55)
                .addComponent(jueves)
                .addGap(64, 64, 64)
                .addComponent(viernes)
                .addGap(56, 56, 56)
                .addComponent(sabado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(domingo)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(previousMonth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextMonth)
                .addGap(18, 18, 18)
                .addComponent(monthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuLabel)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthLabel)
                    .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuLabel)
                    .addComponent(previousMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(separatorCalendaryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunes)
                    .addComponent(martes)
                    .addComponent(miercoles)
                    .addComponent(jueves)
                    .addComponent(viernes)
                    .addComponent(sabado)
                    .addComponent(domingo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void day1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day1ActionPerformed
        dayActionPerformed(1, day1);
    }//GEN-LAST:event_day1ActionPerformed

    private void day2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day2ActionPerformed
        dayActionPerformed(2, day2);
    }//GEN-LAST:event_day2ActionPerformed

    private void day3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day3ActionPerformed
        dayActionPerformed(3, day3);
    }//GEN-LAST:event_day3ActionPerformed

    private void day4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day4ActionPerformed
        dayActionPerformed(4, day4);
    }//GEN-LAST:event_day4ActionPerformed

    private void day5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day5ActionPerformed
        dayActionPerformed(5, day5);
    }//GEN-LAST:event_day5ActionPerformed

    private void day6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day6ActionPerformed
        dayActionPerformed(6, day6);
    }//GEN-LAST:event_day6ActionPerformed

    private void day7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day7ActionPerformed
        dayActionPerformed(7, day7);
    }//GEN-LAST:event_day7ActionPerformed

    private void day8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day8ActionPerformed
        dayActionPerformed(8, day8);
    }//GEN-LAST:event_day8ActionPerformed

    private void day9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day9ActionPerformed
        dayActionPerformed(9, day9);
    }//GEN-LAST:event_day9ActionPerformed

    private void day10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day10ActionPerformed
        dayActionPerformed(10, day10);
    }//GEN-LAST:event_day10ActionPerformed

    private void day11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day11ActionPerformed
        dayActionPerformed(11, day11);
    }//GEN-LAST:event_day11ActionPerformed

    private void day12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day12ActionPerformed
        dayActionPerformed(12, day12);
    }//GEN-LAST:event_day12ActionPerformed

    private void day13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day13ActionPerformed
        dayActionPerformed(13, day13);
    }//GEN-LAST:event_day13ActionPerformed

    private void day14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day14ActionPerformed
        dayActionPerformed(14, day14);
    }//GEN-LAST:event_day14ActionPerformed

    private void day15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day15ActionPerformed
        dayActionPerformed(15, day15);
    }//GEN-LAST:event_day15ActionPerformed

    private void day16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day16ActionPerformed
        dayActionPerformed(16, day16);
    }//GEN-LAST:event_day16ActionPerformed

    private void day17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day17ActionPerformed
        dayActionPerformed(17, day17);
    }//GEN-LAST:event_day17ActionPerformed

    private void day18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day18ActionPerformed
        dayActionPerformed(18, day18);
    }//GEN-LAST:event_day18ActionPerformed

    private void day19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day19ActionPerformed
        dayActionPerformed(19, day19);
    }//GEN-LAST:event_day19ActionPerformed

    private void day20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day20ActionPerformed
        dayActionPerformed(20, day20);
    }//GEN-LAST:event_day20ActionPerformed

    private void day21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day21ActionPerformed
        dayActionPerformed(21, day21);
    }//GEN-LAST:event_day21ActionPerformed

    private void day22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day22ActionPerformed
        dayActionPerformed(22, day22);
    }//GEN-LAST:event_day22ActionPerformed

    private void day23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day23ActionPerformed
        dayActionPerformed(23, day23);
    }//GEN-LAST:event_day23ActionPerformed

    private void day24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day24ActionPerformed
        dayActionPerformed(24, day24);
    }//GEN-LAST:event_day24ActionPerformed

    private void day25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day25ActionPerformed
        dayActionPerformed(25, day25);
    }//GEN-LAST:event_day25ActionPerformed

    private void day26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day26ActionPerformed
        dayActionPerformed(26, day26);
    }//GEN-LAST:event_day26ActionPerformed

    private void day27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day27ActionPerformed
        dayActionPerformed(27, day27);
    }//GEN-LAST:event_day27ActionPerformed

    private void day28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day28ActionPerformed
        dayActionPerformed(28, day28);
    }//GEN-LAST:event_day28ActionPerformed

    private void day29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day29ActionPerformed
        dayActionPerformed(29, day29);
    }//GEN-LAST:event_day29ActionPerformed

    private void day30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day30ActionPerformed
        dayActionPerformed(30, day30);
    }//GEN-LAST:event_day30ActionPerformed

    private void day31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day31ActionPerformed
        dayActionPerformed(31, day31);
    }//GEN-LAST:event_day31ActionPerformed

    private void previousMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousMonthActionPerformed
        month--;
        if (month < 1)
            month = 12;
        monthLabel.setText(getMonth() + " de");
        updateMonthContext();
        updateCalendary();
    }//GEN-LAST:event_previousMonthActionPerformed

    private void nextMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMonthActionPerformed
        month++;
        if (month > 12)
            month = 1;
        monthLabel.setText(getMonth() + " de");
        updateMonthContext();
        updateCalendary();
    }//GEN-LAST:event_nextMonthActionPerformed

    private void yearSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yearSpinnerStateChanged
        year = (int)yearSpinner.getValue();
        if (year < 2022)
        {
            yearSpinner.setValue(2022);
            year = 2022;
        }
        updateCalendary();
    }//GEN-LAST:event_yearSpinnerStateChanged
    
    private void updateMonthContext()
    {
        int days = (int)(28 + (month + Math.floor(month/8)) % 2 + 2 % month + 2 * Math.floor(1/month));
        switch (days)
        {
            case 28:
                monthContext.swapStrategy(new TwentyEightDayMonth());
                break;
            case 30:
                monthContext.swapStrategy(new ThertyDayMonth());
                break;
            case 31:
                monthContext.swapStrategy(new ThertyOneDayMonth());
                break;
        }
    }
    
    private String getMonth()
    {
        switch (month)
        {
            case 1:
                return "Enero";
            case 2:
                return "Febrero";
            case 3:
                return "Marzo";
            case 4:
                return "Abril";
            case 5:
                return "Mayo";
            case 6:
                return "Junio";
            case 7:
                return "Julio";
            case 8:
                return "Agosto";
            case 9:
                return "Septiembre";
            case 10:
                return "Octubre";
            case 11:
                return "Noviembre";
            case 12:
                return "Diciembre";
            default:
                return "Error";
        }
    }
    
    public static void run(Calendary calendary)
    {        
        GuiMenu.setLookAndFeel();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                if (Instance == null)
                    Instance = new GuiMenu(calendary);
                Instance.setVisible(true);
            }
        });
    }
    
    public static void exit()
    {
        Instance.dispose();
        System.exit(0);
    }
    
    private static void setLookAndFeel()
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Dark".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton day1;
    private javax.swing.JButton day10;
    private javax.swing.JButton day11;
    private javax.swing.JButton day12;
    private javax.swing.JButton day13;
    private javax.swing.JButton day14;
    private javax.swing.JButton day15;
    private javax.swing.JButton day16;
    private javax.swing.JButton day17;
    private javax.swing.JButton day18;
    private javax.swing.JButton day19;
    private javax.swing.JButton day2;
    private javax.swing.JButton day20;
    private javax.swing.JButton day21;
    private javax.swing.JButton day22;
    private javax.swing.JButton day23;
    private javax.swing.JButton day24;
    private javax.swing.JButton day25;
    private javax.swing.JButton day26;
    private javax.swing.JButton day27;
    private javax.swing.JButton day28;
    private javax.swing.JButton day29;
    private javax.swing.JButton day3;
    private javax.swing.JButton day30;
    private javax.swing.JButton day31;
    private javax.swing.JButton day4;
    private javax.swing.JButton day5;
    private javax.swing.JButton day6;
    private javax.swing.JButton day7;
    private javax.swing.JButton day8;
    private javax.swing.JButton day9;
    private javax.swing.JLabel domingo;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jueves;
    private javax.swing.JLabel lunes;
    private javax.swing.JLabel martes;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JLabel miercoles;
    private javax.swing.ButtonGroup monthButtons;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JButton nextMonth;
    private javax.swing.JButton previousMonth;
    private javax.swing.JLabel sabado;
    private javax.swing.JSeparator separatorCalendaryDate;
    private javax.swing.JLabel viernes;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables
}
